name: Test Builds

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  FLUTTER_MAIN_FILE: lib/main_prod.dart
  IPA_FILE: release.ipa
  AAB_FILE: app-release.aab
  SYMBOLS_PATH: packages/genesis_mobile/build/app/outputs/symbols

jobs:
  build_android:
    env:
      GITHUB_USER: ${{ secrets.REPO_USER }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DUMMY_VARIABLE: ${{ secrets.GITHUB_TOKEN }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - run: echo "$GITHUB_USER" >> $GITHUB_PATH
      - run: echo $DUMMY_VARIABLE
      - run: echo "HOWDY!"
      